categories:
- Astronomy
description: eROSITA
homepage_url: null
long_description: eROSITA
name: erosita_astro_tool
owner: astroteam
remote_repository_url: https://github.com/esg-epfl-apc/tools-astro/tree/main/tools
type: unrestricted
