name: astropytools
owner: astroteam
type: unrestricted
categories: 
- Astronomy
description: AstropyTools library contains Galaxy tools for elementary Astrophysical operations 
long_description: |
  Astropy is a python library containing basic astrophysical tools and interfaces.
  This package makes some of the operations available as Galaxy tools 

homepage_url: https://github.com/astropy/astropy

remote_repository_url: https://github.com/esg-epfl-apc/tools-astro/tree/main/tools/astropytools
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} (from the astropy tool suite)"
suite:
  name: "suite_astropytools"
  description: "A suite of Galaxy tools to manipulate astrophysical data"
  type: repository_suite_definition
