categories:
- Astronomy
description: ProtoIceCube
homepage_url: null
long_description: ProtoIceCube
name: proto_ice_cube_astro_tool
owner: astroteam
remote_repository_url: https://github.com/esg-epfl-apc/tools-astro/tree/main/tools
type: unrestricted
