categories:
- Astronomy
description: Basic analysis of Data Level 3 public data sample of HESS gamma-ray telescope
homepage_url: null
long_description: Basic analysis of Data Level 3 public data sample of HESS gamma-ray
  telescope
name: HESS
owner: astroteam
remote_repository_url: https://github.com/esg-epfl-apc/tools-astro/tree/main/tools
type: unrestricted
