categories:
- Astronomy
description: Auger
homepage_url: null
long_description: Auger
name: auger_astro_tool
owner: astroteam
remote_repository_url: https://github.com/esg-epfl-apc/tools-astro/tree/main/tools
type: unrestricted
