categories:
- Astronomy
description: MWA
homepage_url: null
long_description: MWA
name: mwa_astro_tool
owner: astroteam
remote_repository_url: https://github.com/esg-epfl-apc/tools-astro/tree/main/tools
type: unrestricted
