categories:
- Astronomy
description: integral-observed
homepage_url: null
long_description: integral-observed
name: integral_observed_astro_tool
owner: astroteam
remote_repository_url: https://github.com/esg-epfl-apc/tools-astro/tree/main/tools
type: unrestricted
